// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRCQshTwdz2l0rn3MtvTLFyjNXMABHDr0',
    appId: '1:798612753910:android:b923edcdbc9f396c72cbd7',
    messagingSenderId: '798612753910',
    projectId: 'espy-53470',
    storageBucket: 'espy-53470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxAfL0ic-qZsJM7E-6o921Xd8Kk_MtTHc',
    appId: '1:798612753910:ios:0c8e1b03e115a59472cbd7',
    messagingSenderId: '798612753910',
    projectId: 'espy-53470',
    storageBucket: 'espy-53470.appspot.com',
    androidClientId: '798612753910-0l4mgr27thbjlgfm5eau4rokvmr4ivit.apps.googleusercontent.com',
    iosClientId: '798612753910-0nou31b6dsgc9ibvqluemvuse7e2tmpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.espy',
  );
}
